### ISSUE TITLE
Avoid use of vim.bindeval() in Python

### ISSUE THREAD

**Issue by weslem** [google/vim-maktaba#159] opened 2015-08-05 22:26 UTC
The `bindeval()` method is only available in newer version of vim, reducing compatibility. Neovim's remote plugin architecture is fundamentally incompatible with `bindeval()` as well.

The two locations in maktabajson.py should be easily replaced with `eval()`, assuming the performance remains acceptable.

**Comment by dbarnett** [comment] 2015-08-05 22:30
Dupe of #158.

**Closed by dbarnett** 2015-08-05 22:30 UTC
